package:
  name: swig
  version: 3.0.8

source:
  fn: swig-3.0.8.tar.gz
  url: http://prdownloads.sourceforge.net/swig/swig-3.0.8.tar.gz
  md5: c96a1d5ecb13d38604d7e92148c73c97

build:
  detect_binary_files_with_prefix: True

requirements:
  build:
    - gcc
    - zlib
    - pcre
    - python

  run:
    - libgcc
    - zlib
    - pcre

test:
  commands:
    - swig -help

about:
    home: http://www.swig.org/
    license: GPLv3
