package:
  name: dolfin-adjoint
  version: "1.6.0"

source:
  fn: dolfin-adjoint-1.6.0.tar.gz
  url: https://bitbucket.org/quang-ha/dolfin-adjoint/downloads/dolfin-adjoint-1.6.0.tar.gz 
  md5: d62f4076296e2704b11783a1cf3ce449

build:
  number: 2

requirements:
  build:
    - dolfin ==1.6.0

  run:
    - dolfin ==1.6.0

test:
  requires:
    - gcc

about:
  home: dolfin-adjoint.org
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'libadjoint: library for the high-level algorithmic differentiation of scientific models'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
